import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  overviewDocsSidebar: [
    {
      type: "category",
      label: "Projeto",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "projeto",
        },
      ],
    },

    {
      type: "category",
      label: "Requisitos",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "requirements",
        },
      ],
    },

    {
      type: "category",
      label: "Desenvolvimento",
      collapsed: false,
      items: [
        {
          type: "autogenerated",
          dirName: "desenvolvimento",
        },
      ],
    },
  ],
};

export default sidebars;
