apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-certs-production-pv
  namespace: default
  labels:
    app: registry
spec:
  volumeMode: Filesystem
  hostPath:
    path: /mnt/storage/registry/certs
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: x-ladesa-infra-host
              operator: In
              values:
                - "yes"
