apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-certs-pvc
  namespace: default
  labels:
    app: registry
spec:
  storageClassName: ""
  volumeName: registry-certs-production-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
