apiVersion: apps/v1
kind: Deployment
metadata:
  name: ladesa-ro-web
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ladesa-ro-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: ladesa-ro-web
    spec:
      containers:
        - name: ladesa-ro-web
          image: "nginx:1"
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /
              port: 3000
            failureThreshold: 30
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: ladesa-ro-web-config
          resources:
            requests:
              cpu: "50m"
              memory: "1Gi"
            limits:
              memory: "2Gi"
              cpu: "2"
