kind: Deployment
apiVersion: apps/v1
metadata:
  name: hello-world
  namespace: default
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: hello-world
          image: traefik/whoami:latest
          # image: "debian:12"
          # command: ["/bin/bash"]
          # args: ["-c", "tail -f /dev/null"]
          ports:
            - name: web
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: default
spec:
  ports:
    - name: web
      port: 8080
      targetPort: web
  selector:
    app: hello-world
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: default
spec:
  rules:
    - host: whoami.ladesa.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world
                port:
                  name: web
# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: whoami-ingress
#   namespace: default
# spec:
#   entryPoints:
#     - web
#   routes:
#     - kind: Rule
#       match: PathPrefix(`/`)
#       services:
#         - name: hello-world
#           namespace: default
#           port: web
