apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ladesa-ro-web-ingress
spec:
  rules:
    - host: dev.ladesa.com.br
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ladesa-ro-web
                port:
                  name: web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ladesa-ro-web-ingress-redirect
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      return 301 $scheme://dev.ladesa.com.br$request_uri;
spec:
  rules:
    - host: luna.sisgha.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ladesa-ro-web
                port:
                  name: web
