apiVersion: apps/v1
kind: Deployment
metadata:
  name: ladesa-ro-docs-packages-npm-api-client-fetch
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ladesa-ro-docs-packages-npm-api-client-fetch
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        name: ladesa-ro-docs-packages-npm-api-client-fetch
    spec:
      containers:
        - name: ladesa-ro-docs-packages-npm-api-client-fetch
          image: "nginx:1"
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 15
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "250Mi"
            limits:
              memory: "500Mi"
              cpu: "1"
