apiVersion: v1
kind: PersistentVolume
metadata:
  name: quay-app-log-pv
  namespace: default
  labels:
    app: quay
spec:
  volumeMode: Filesystem
  hostPath:
    path: /mnt/storage/quay/logs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: default
    name: quay-app-log-pvc
  persistentVolumeReclaimPolicy: Retain
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: x-ladesa-infra-host
              operator: In
              values:
                - "yes"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quay-app-log-pvc
  namespace: default
  labels:
    app: quay
spec:
  storageClassName: ""
  volumeName: quay-app-log-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
