applicationName: ladesa-ro-docs

deployment:
  enabled: true

  replicas: 1

  image:
    repository: registry.ladesa.com.br/docs
    tag: production
    pullPolicy: Always

  imagePullSecrets:
    - name: ladesa-registry-pull-secret

  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  resources:
    requests:
      cpu: "50m"
      memory: "1Gi"
    limits:
      memory: "2Gi"
      cpu: "2"

  containerSecurityContext:
    runAsNonRoot: false
    readOnlyRootFilesystem: false

  ports:
    - containerPort: 80
      name: web-port

  readinessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 5
    periodSeconds: 10
  livenessProbe:
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 15
  startupProbe:
    httpGet:
      path: /
      port: 80
    failureThreshold: 30
    periodSeconds: 10

service:
  enabled: true
  type: NodePort
  ports:
    - name: web-service
      port: 80
      targetPort: web-port

ingress:
  enabled: true
  hosts:
    - host: docs.ladesa.com.br
      paths:
        - path: /
          pathType: ImplementationSpecific
          servicePort: web-service
