apiVersion: v2
name: docs
description: Documentacao do Ladesa, servida em docs.ladesa.com.br
type: application
version: 0.1.0
dependencies:
  - name: application
    version: 6.0.2
    repository: https://stakater.github.io/stakater-charts
