---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ladesa-ro-docs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd-image-updater.argoproj.io/image-list: docs=ghcr.io/ladesa-ro/docs/docs
    argocd-image-updater.argoproj.io/docs.update-strategy: digest
    argocd-image-updater.argoproj.io/docs.helm.image-tag: application.deployment.image.digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: ladesa-satellites
  source:
    repoURL: https://github.com/ladesa-ro/docs.git
    targetRevision: main
    path: gitops/apps/docs
    helm:
      releaseName: ladesa-ro-docs
      valueFiles:
        - values-development.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ladesa-ro-development
  revisionHistoryLimit: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - FailOnSharedResource=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
