name: "Continuous Deployment"

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  cd_build_push:
    name: "Build and Push"
    runs-on: ubuntu-latest

    environment:
      name: production

    env:
      BUILD_IMAGE_NAME: production
      BUILD_IMAGE_TAG: production

    steps:
      - uses: actions/checkout@v4

      - uses: ladesa-ro/esteira-ci-cd/actions/prepare-images-builder@main
        with:
          setup-qemu: "false"
          push-image: "true"
          push-image-registry-url: ${{ secrets.REGISTRY_URL }}
          push-image-registry-username: ${{ secrets.REGISTRY_USERNAME }}
          push-image-registry-token: ${{ secrets.REGISTRY_TOKEN }}

      - uses: ladesa-ro/esteira-ci-cd/actions/image-build-push@main
        with:
          image-tag: ${{ env.BUILD_IMAGE_TAG }}
          image-name: ${{ env.BUILD_IMAGE_NAME  }}

          build-image: "true"
          build-target-tag: "runtime"

          push-image: "true"
          push-image-registry-url: ${{ secrets.REGISTRY_URL }}

  cd_deploy:
    name: Deploy to Cluster

    runs-on: deploy
    needs: [cd_build_push]

    environment:
      name: production
      url: https://docs.ladesa.com.br

    env:
      HELM_RELEASE_NAME: ladesa-ro-docs
      K8S_NAMESPACE: ladesa-ro-production
      K8S_DEPLOYMENT: ladesa-ro-docs
    steps:
      - uses: actions/checkout@v4

      - shell: bash
        run: |
          helm upgrade -i ${HELM_RELEASE_NAME} --repo https://stakater.github.io/stakater-charts application --version 6.0.2 --namespace=${K8S_NAMESPACE} -f ./.github/workflows/deploy/values.prod.yml;

          kubectl rollout restart \
            deployment.apps/${K8S_DEPLOYMENT} \
            --namespace ${K8S_NAMESPACE} \
          ;
