name: "CD: Continuous Deployment"

on:
  push:
    branches:
      - main

jobs:
  cd-build-push:
    name: "CD: Build and Push"
    uses: ./.github/workflows/cd-build-and-push.yml
    secrets: inherit

  cd-build-push-deploy:
    name: "CD: Deploy"
    uses: ./.github/workflows/cd-deploy.yml
    secrets: inherit
    needs: [cd-build-push]
